#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  corda-driver:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
    container_name: corda-driver-${NETWORK_NAME}
    environment:
      - DRIVER_PORT=${DRIVER_PORT}
    ports:
      - "${DRIVER_PORT}:${DRIVER_PORT}"
    command: sh -c "./bin/corda-driver"

networks:
  default:
    external:
      name: ${EXTERNAL_NETWORK}
