openapi: 3.0.3
info:
  title: SATP Gateway Client (Business Logic Orchestrator)
  version: 0.0.2
  description: |-
    SATP is a protocol operating between two gateways that conducts the transfer of a digital asset from one gateway to another. The protocol establishes a secure channel between the endpoints and implements a 2-phase commit to ensure the properties of transfer atomicity, consistency, isolation and durability.

    This API defines the gateway client facing API (business logic orchestrator, or BLO), which is named API-Type 1 in the SATP-Core specification.

    **Additional Resources**:
    - [Proposed SATP Charter](https://datatracker.ietf.org/doc/charter-ietf-satp/)
    - [SATP Core draft](https://datatracker.ietf.org/doc/draft-ietf-satp-core)
    - [SATP Crash Recovery draft](https://datatracker.ietf.org/doc/draft-belchior-satp-gateway-recovery/)
    - [SATP Architecture draft](https://datatracker.ietf.org/doc/draft-ietf-satp-architecture/)
    - [SATP Use-Cases draft](https://datatracker.ietf.org/doc/draft-ramakrishna-sat-use-cases/)
    - [SATP Data sharing draft](https://datatracker.ietf.org/doc/draft-ramakrishna-satp-data-sharing)
    - [SATP View Addresses draft](https://datatracker.ietf.org/doc/draft-ramakrishna-satp-views-addresses)
  contact:
    name: Hyperledger Cacti
  x-logo:
    altText: Cacti logo
    backgroundColor: '#fafafa'
    url: https://github.com/hyperledger/cacti/blob/main/images/HL_Cacti_Logo_Color.png
externalDocs:
  description: For more information about the SATP Gateway Client, refer to the official documentation.
  url: https://github.com/hyperledger/cacti/tree/main/packages/cactus-plugin-satp-hermes/README.md
servers:
  - url: http://{host}:{port}/api/v1/@hyperledger/cactus-plugin-satp-hermes
    description: Development server
    variables:
      host:
        default: localhost
      port:
        default: '3011'
tags:
  - name: transaction
    description: API endpoints for interacting with blockchains via gateways
  - name: admin
    description: API endpoints for fetching information on SATP sessions
paths:
  /api/v1/@hyperledger/cactus-plugin-satp-hermes/transact:
    post:
      tags:
        - transaction
      summary: Submit a transaction intent
      description: Allows users to queue intents for transactions based on specified parameters.
      operationId: Transact
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas.yml#/TransactRequest
        required: true
      responses:
        '200':
          description: Transaction successfully queued
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/TransactResponse
        default:
          description: An error occurred
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/APIError
  /api/v1/@hyperledger/cactus-plugin-satp-hermes/cancel:
    post:
      tags:
        - transaction
      summary: Cancel a transaction session
      description: Attempts to cancel a previously submitted transaction intent using its session ID.
      operationId: Cancel
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/@hyperledger/cactus-plugin-satp-hermes/cancel
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas.yml#/CancelRequest
        required: true
      responses:
        '200':
          description: Transaction cancellation attempted
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/CancelResponse
        default:
          description: An error occurred or transaction cannot be cancelled
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/APIError
  /api/v1/@hyperledger/cactus-plugin-satp-hermes/status:
    get:
      summary: Get SATP current session data
      description: Retrieve the status of a SATP session
      operationId: GetStatus
      tags:
        - admin
      x-hyperledger-cacti:
        http:
          verbLowerCase: get
          path: /api/v1/@hyperledger/cactus-plugin-satp-hermes/status
      parameters:
        - name: SessionID
          in: query
          schema:
            $ref: ./schemas.yml#/SessionID
          required: true
          description: Unique identifier for the session.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/StatusResponse
        '400':
          description: Bad request
        '404':
          description: Transaction not found
        '500':
          description: Internal server error
  /api/v1/@hyperledger/cactus-plugin-satp-hermes/continue:
    post:
      tags:
        - admin
      summary: Continue a paused transaction session
      description: Attempts to continue a previously paused transaction intent, resuming its execution.
      operationId: Continue
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/@hyperledger/cactus-plugin-satp-hermes/continue
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas.yml#/ContinueRequest
        required: true
      responses:
        '200':
          description: Transaction continuation attempted
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/ContinueResponse
        default:
          description: An error occurred or transaction cannot be continued
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/APIError
  /api/v1/@hyperledger/cactus-plugin-satp-hermes/pause:
    post:
      tags:
        - admin
      summary: Pause a transaction session
      description: Attempts to pause a previously submitted transaction intent, temporarily halting its execution.
      operationId: Pause
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/@hyperledger/cactus-plugin-satp-hermes/pause
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas.yml#/PauseRequest
        required: true
      responses:
        '200':
          description: Transaction pause attempted
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/PauseResponse
        default:
          description: An error occurred or transaction cannot be paused
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/APIError
 
  /api/v1/@hyperledger/cactus-plugin-satp-hermes/integrations:
    get:
      tags:
        - transaction
      summary: Get supported integrations
      description: Retrieves metadata about each supported blockchain networks, chains, and other systems.
      operationId: GetIntegrations
      x-hyperledger-cacti:
        http:
          verbLowerCase: get
          path: /api/v1/@hyperledger/cactus-plugin-satp-hermes/integrations
      responses:
        "200":
          description: A list of supported systems.
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/Chains
        default:
          description: An error occurred
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/APIError
  /api/v1/@hyperledger/cactus-plugin-satp-hermes/routes:
    get:
      description: Get a list of possible routes for swapping one asset for another across multiple exchanges
      summary: Get a list of routes for a gateway-to-gateway asset transfer
      tags:
        - transaction
      operationId: GetRoutes
      x-hyperledger-cacti:
        http:
          verbLowerCase: get
          path: /api/v1/@hyperledger/cactus-plugin-satp-hermes/routes
      parameters:
        - name: fromNetworkID
          in: query
          schema:
            $ref: ./schemas.yml#/DLTNetworkID
          required: true
          description: The sending DLT Network.
        - name: fromAmount
          in: query
          schema:
            $ref: ./schemas.yml#/AmountString
          required: true
          description: The amount that should be sent including all decimals.
        - name: fromToken
          in: query
          schema:
            $ref: ./schemas.yml#/Address
          required: true
          description: The token that should be transferred. Can be the address or the symbol.
        - name: toDLTNetwork
          in: query
          schema:
            $ref: ./schemas.yml#/DLTNetworkID
          required: true
          description: The receiving DLT Network.
        - name: toToken
          in: query
          schema:
            $ref: ./schemas.yml#/Address
          required: true
          description: The token that should be transferred to. Can be the address or the symbol.
        - name: fromAddress
          in: query
          schema:
            $ref: ./schemas.yml#/Address
          required: true
          description: The sending wallet address.
        - name: toAddress
          in: query
          schema:
            $ref: ./schemas.yml#/Address
          required: true
          description: The receiving wallet address. If none is provided, the fromAddress will be used.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/RoutesResponse
        default:
          description: An error occurred
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/APIError
  /api/v1/@hyperledger/cactus-plugin-satp-hermes/audit:
    get:
      tags:
        - admin
      summary: Audit transactions
      description: Audits transactions based on provided filters such as start and end dates. Optionally includes proofs generated from each gateway transaction.
      operationId: GetAudit
      x-hyperledger-cacti:
        http:
          verbLowerCase: get
          path: /api/v1/@hyperledger/cactus-plugin-satp-hermes/audit
      parameters:
        - name: auditStartDate
          in: query
          description: The start date for the audit period.
          required: false
          schema:
            type: string
            format: date-time
        - name: auditEndDate
          in: query
          description: The end date for the audit period.
          required: false
          schema:
            type: string
            format: date-time
        - name: includeProofs
          in: query
          description: Include proofs generated from each gateway transaction.
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Audit results
          content:
            application/json:
              schema:
                $ref: ./schemas.yml#/getAuditResponse
components:
  schemas:
    $ref: ./schemas.yml
