blpRegistry:
  -
    businessLogicID: guks32pf
    validatorID: [84jUisrs, r9IS4dDf]

logLevel: debug

applicationHostInfo:
  hostName: http://localhost # please change hostName to your IP address
  hostPort: 5034

socketOptions:
  rejectUnauthorized: false
  reconnection: false
  timeout: 20000

verifier:
  maxCounterRequestID: 100
  syncFunctionTimeoutMillisecond: 5000

appRouters:
  -
    path: /api/v1/bl/trades/
    routerJs: ../../../../../../examples/discounted-cartrade/trades.js
  -
    path: /api/v1/bl/asset/
    routerJs: ../../../../../../examples/discounted-cartrade/asset.js
  -
    path: /api/v1/bl/balance/
    routerJs: ../../../../../../examples/discounted-cartrade/balance.js
  -
    path: /api/v1/bl/cars/
    routerJs: ../../../../../../examples/discounted-cartrade/cars.js
  # abolish template-trade
  # -
    # path: /api/v1/bl/template-trade/
    # routerJs: ../../../../../../examples/discounted-cartrade/template-trade.js

