---
    name: coverage_typescript
    
    env:
      NODEJS_VERSION: v20.20.0
    on:
      workflow_run:
        workflows: 
         - Cactus_CI
        types:
          - completed
    
    jobs:
      generate_coverage_report:
        runs-on: ubuntu-22.04
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
          - name: Check out repository
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
    
          - name: Set up Node.js
            uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b #v4.0.3
            with:
              node-version: ${{ env.NODEJS_VERSION }}
    
          - name: Restore Yarn Cache
            uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf #v4.2.2
            with:
              path: ./.yarn/
              key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
              restore-keys: |
                ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
    
          - name: Install dependencies and istanbul-merge
            run: |
              yarn install
              yarn add istanbul-merge --dev
    
          - name: Download coverage reports
            uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
            with:
              run-id: ${{ github.event.workflow_run.id }}
              github-token: ${{ secrets.GITHUB_TOKEN }}
              path: ./code-coverage-ts/
    
          - name: Merge and generate coverage reports
            run: |
              ls -R ./code-coverage-ts/**/**/
              npx istanbul-merge --out coverage.json ./code-coverage-ts/coverage-reports-*/*/coverage-final.json
              npx istanbul report --include coverage.json --dir cacti html
              npx istanbul report --include coverage.json --dir cacti text
              npx istanbul report --include coverage.json --dir cacti text-summary
    
          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 #v4.0.1
            with:
              name: code-coverage-report
              fail_ci_if_error: true
              token: ${{ secrets.CODECOV_TOKEN }}