# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: CC-BY-4.0

name: Deploy Docs (Github Pages)

on:
  push:
    branches:
      - main

    paths:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  SITE_URL: https://${{ github.repository_owner }}.github.io/cacti
  NODEJS_VERSION: v20.20.0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  deploy-docs:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
    steps:
      - name: Use Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b #v4.0.3
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Use Python 3.x
        uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb #v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: docs

      - name: Build packages
        run: npm run configure

      - name: Build markdown for openapi specs
        run: 'python3 docs/scripts/publish_openapi.py'
        
      - name: Build and publish
        run: git pull && mkdocs gh-deploy
        working-directory: docs
