name: Deploy Weaver Fabric CC Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'core/network/fabric-interop-cc/Makefile.variables.docker'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  relay-image:
    if: github.repository_owner == 'hyperledger-labs'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push
        run: make push-image
        working-directory: core/network/fabric-interop-cc
        
      - name: Push latest tag
        run: make push-image-latest
        working-directory: core/network/fabric-interop-cc